import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "openai/gpt-oss-20b"


def stylometric_signal(text):
    sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in sentences if s.strip()]

    words = re.findall(r"\b[\w'-]+\b", text.lower())

    if not words:
        return 0.5

    sentence_lengths = [len(re.findall(r"\b[\w'-]+\b", s)) for s in sentences]

    if len(sentence_lengths) > 1:
        variance = statistics.pvariance(sentence_lengths)
    else:
        variance = 0

    unique_ratio = len(set(words)) / len(words)

    punctuation = len(re.findall(r"[,;:!?]", text)) / max(len(words), 1)

    # More uniform writing tends to push the score upward.
    uniformity = max(0, 1 - min(variance / 100, 1))

    # Combine structural indicators.
    score = (
        0.45 * uniformity
        + 0.35 * unique_ratio
        + 0.20 * min(punctuation * 10, 1)
    )

    return round(max(0, min(score, 1)), 4)


def llm_signal(text):
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))

    prompt = f"""
You are an AI-text attribution classifier.

Analyze the following text and estimate how likely it is to have been
generated by an AI language model.

Return ONLY valid JSON in exactly this format:

{{"ai_score": 0.0}}

Where:
- 0.0 means very unlikely to be AI-generated
- 1.0 means very likely to be AI-generated
- use a decimal between 0 and 1
- do not explain your answer

Text:
{text}
"""

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        temperature=0,
    )

    content = response.choices[0].message.content.strip()

    match = re.search(r'"ai_score"\s*:\s*(0(?:\.\d+)?|1(?:\.0+)?)', content)

    if not match:
        raise ValueError(f"Could not parse LLM score: {content}")

    score = float(match.group(1))
    return round(max(0, min(score, 1)), 4)


def make_label(attribution, confidence):
    if attribution == "likely_ai":
        return (
            "Likely AI-generated: Our analysis found stronger signals "
            "associated with AI-generated text. This result is an estimate, "
            "not proof of authorship."
        )

    if attribution == "likely_human":
        return (
            "Likely human-written: Our analysis found stronger signals "
            "associated with human-written text. This result is an estimate, "
            "not proof of authorship."
        )

    return (
        "Uncertain attribution: The signals were mixed or not strong enough "
        "to make a confident determination. This result is an estimate, "
        "not proof of authorship."
    )


def analyze_text(text):
    llm_score = llm_signal(text)
    stylometric_score = stylometric_signal(text)

    # Both signals represent AI likelihood.
    confidence = (
        0.65 * llm_score
        + 0.35 * stylometric_score
    )

    confidence = round(max(0, min(confidence, 1)), 4)

    if confidence >= 0.65:
        attribution = "likely_ai"
    elif confidence <= 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    label = make_label(attribution, confidence)

    return {
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label,
    }